name: 更新中国IP列表并生成GeoIP2数据库

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    name: 生成GeoIP2数据库
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 设置 Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
        id: go

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 获取依赖项
        run: go get -v -t -d ./...

      - name: 创建 dist 文件夹
        run: mkdir -p dist

      - name: 编译 GeoIP 转换二进制文件 (Golang)
        run: ./build.sh

      - name: 获取 CN IP 列表
        run: |
          curl -LR -o dist/ipip_net.txt "https://raw.githubusercontent.com/zhufengme/block_cn_files/refs/heads/master/cn_ip_list.txt"
          # 移除 "echo >> dist/chunzhen.txt" 行，除非确实需要

      - name: 合并并去重 IP 列表
        run: |
          cat dist/*.txt | dist/dedup > dist/CN-ip-cidr.txt

      - name: 生成 GeoIP2 数据库
        run: |
          cd dist
          ./ipip2mmdb -s ./CN-ip-cidr.txt -d Country.mmdb
          cd ..

      - name: 检查更改
        id: changes
        run: |
          git fetch origin release:release || git checkout -b release
          if ! diff -q dist/Country.mmdb Country.mmdb || ! diff -q dist/CN-ip-cidr.txt CN-ip-cidr.txt; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: 推送工件到 release 分支
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "10215166+Hackl0us@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release || git checkout -b release
          cp -f dist/CN-ip-cidr.txt ./
          cp -f dist/Country.mmdb ./
          git add CN-ip-cidr.txt Country.mmdb
          git commit -m "Updated at $(date)" || echo "No changes to commit"
          git push origin release
